services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    expose:
      - "5672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
  web:
    tty: true
    stdin_open: true
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3002 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - gems_cache:/usr/local/bundle
    ports:
      - "3002:3002"
    depends_on:
      - db
      - rabbitmq

volumes:
  gems_cache:
